echo Building Android Package
rm -rf www/*
cp -r ../distro/* www
rm www/AUTOGENERATED
cordova build android --release
cp platforms/android/build/outputs/apk/android-release-unsigned.apk .
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore exodus.keystore android-release-unsigned.apk exodus_keystore
rm exodus.apk
/Volumes/Macintosh\ HD/Users/slash/Software/adt-bundle-mac-x86_64-20130717/sdk/build-tools/23.0.1/zipalign -v 4 android-release-unsigned.apk exodus.apk
rm android-release-unsigned.apk